export const contractABI = [
  {
    type: "function",
    name: "addExpense",
    inputs: [
      { name: "_expname", type: "string", internalType: "string" },
      { name: "_paidby", type: "string", internalType: "string" },
      { name: "_payerAddress", type: "address", internalType: "address" },
      { name: "_participants", type: "address[]", internalType: "address[]" },
      { name: "_participantNames", type: "string[]", internalType: "string[]" },
      { name: "_paddress", type: "string", internalType: "string" },
      { name: "_amt", type: "uint256", internalType: "uint256" },
      { name: "_status", type: "uint8", internalType: "enum Storage.Status" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "expenseId",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "expenses",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "expname", type: "string", internalType: "string" },
      { name: "paidby", type: "string", internalType: "string" },
      { name: "payerAddress", type: "address", internalType: "address" },
      { name: "paddress", type: "string", internalType: "string" },
      { name: "amt", type: "uint256", internalType: "uint256" },
      { name: "shareamount", type: "uint256", internalType: "uint256" },
      { name: "status", type: "uint8", internalType: "enum Storage.Status" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getAllPaymentRequests",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple[]",
        internalType: "struct Storage.PaymentRequest[]",
        components: [
          { name: "from", type: "address", internalType: "address" },
          { name: "to", type: "address", internalType: "address" },
          { name: "amount", type: "uint256", internalType: "uint256" },
          { name: "reason", type: "string", internalType: "string" },
          { name: "isPaid", type: "bool", internalType: "bool" },
          { name: "timestamp", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getBadDebtors",
    inputs: [{ name: "_id", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "address[]", internalType: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getExpense",
    inputs: [{ name: "_id", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "expname", type: "string", internalType: "string" },
      { name: "paidby", type: "string", internalType: "string" },
      { name: "payerAddress", type: "address", internalType: "address" },
      { name: "paddress", type: "string", internalType: "string" },
      { name: "amt", type: "uint256", internalType: "uint256" },
      { name: "shareamount", type: "uint256", internalType: "uint256" },
      { name: "status", type: "uint8", internalType: "enum Storage.Status" },
      { name: "participants", type: "address[]", internalType: "address[]" },
      { name: "participantNames", type: "string[]", internalType: "string[]" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getLength",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getParticipants",
    inputs: [{ name: "_id", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "", type: "address[]", internalType: "address[]" },
      { name: "", type: "string[]", internalType: "string[]" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPaymentRequest",
    inputs: [{ name: "requestId", type: "uint256", internalType: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct Storage.PaymentRequest",
        components: [
          { name: "from", type: "address", internalType: "address" },
          { name: "to", type: "address", internalType: "address" },
          { name: "amount", type: "uint256", internalType: "uint256" },
          { name: "reason", type: "string", internalType: "string" },
          { name: "isPaid", type: "bool", internalType: "bool" },
          { name: "timestamp", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPaymentRequestCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPendingRequests",
    inputs: [{ name: "debtor", type: "address", internalType: "address" }],
    outputs: [
      {
        name: "",
        type: "tuple[]",
        internalType: "struct Storage.PaymentRequest[]",
        components: [
          { name: "from", type: "address", internalType: "address" },
          { name: "to", type: "address", internalType: "address" },
          { name: "amount", type: "uint256", internalType: "uint256" },
          { name: "reason", type: "string", internalType: "string" },
          { name: "isPaid", type: "bool", internalType: "bool" },
          { name: "timestamp", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getShareAmount",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getStatus",
    inputs: [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "markParticipantPaid",
    inputs: [
      { name: "_id", type: "uint256", internalType: "uint256" },
      { name: "_participant", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "payRequest",
    inputs: [{ name: "requestId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "paymentRequests",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "from", type: "address", internalType: "address" },
      { name: "to", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
      { name: "reason", type: "string", internalType: "string" },
      { name: "isPaid", type: "bool", internalType: "bool" },
      { name: "timestamp", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pendingRequests",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "requestPayment",
    inputs: [
      { name: "to", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
      { name: "reason", type: "string", internalType: "string" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "requestPaymentFromPayer",
    inputs: [{ name: "_expenseId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "resetexp",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateStatus",
    inputs: [
      {
        name: "_newStatus",
        type: "uint8",
        internalType: "enum Storage.Status",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "ExpenseAdded",
    inputs: [
      { name: "id", type: "uint256", indexed: true, internalType: "uint256" },
      {
        name: "expname",
        type: "string",
        indexed: false,
        internalType: "string",
      },
      { name: "amt", type: "uint256", indexed: false, internalType: "uint256" },
      {
        name: "participantCount",
        type: "uint8",
        indexed: false,
        internalType: "uint8",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ParticipantPaid",
    inputs: [
      {
        name: "expenseId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "participant",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PaymentCompleted",
    inputs: [
      {
        name: "requestId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      { name: "from", type: "address", indexed: true, internalType: "address" },
      { name: "to", type: "address", indexed: true, internalType: "address" },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PaymentRequested",
    inputs: [
      {
        name: "requestId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      { name: "from", type: "address", indexed: true, internalType: "address" },
      { name: "to", type: "address", indexed: true, internalType: "address" },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "StatusUpdated",
    inputs: [
      { name: "id", type: "uint256", indexed: true, internalType: "uint256" },
      {
        name: "newStatus",
        type: "uint8",
        indexed: false,
        internalType: "enum Storage.Status",
      },
    ],
    anonymous: false,
  },
];
